version: "3.6"

services:
  database:
    image: "postgres"
    container_name: "scoutbase-postgres"
    restart: "unless-stopped"
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    env_file:
      - "./back-end/.db.env"
    ports:
      - "5432:5432"      
    networks: 
      - "scoutnet"

volumes:
  pgdata:

networks:
  scoutnet:
    name: "scoutnet"

