version: "3.6"

services:
  database:
    image: "postgres"
    container_name: "scoutbase-postgres"
    restart: "unless-stopped"
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    env_file:
      - "./back-end/.db.env"
    ports:
      - "5432:5432"      
    networks: 
      - "scoutnet"
      - "default"
  
  server:
    build:
      context: "./back-end"
    image: "scoutbase/code-challenge-backend"
    container_name: "scoutbase-server"
    restart: "unless-stopped"
    depends_on:
      - "database"
    ports:
      - "5000:5000"
    networks:
      - "scoutnet"
      - "default"

volumes:
  pgdata:

networks:
  scoutnet:
    name: "scoutnet"
    driver: "bridge"
